version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../..:/workspaces:cached

  database:
    image: mariadb:latest
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "wordpress"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_ROOT_PASSWORD: ""

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  database:
