name: hb
on:
    push:
        branches:
            - fse
    workflow_dispatch:
jobs:
    pack:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Pack files for release
                run: |
                    zip -r brontosaurus-theme.zip . \
                        -i "parts/*" \
                        -i "templates/*" \
                        -i "functions.php" \
                        -i "index.php" \
                        -i "style.css" \
                        -i "theme.json"

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: deps
                    path: brontosaurus-theme.zip

    deploy_staging:
        runs-on: ubuntu-latest
        if: ${{ github.ref_name == 'fse' && github.event_name == 'push' && ! startsWith(github.ref_name, 'dependabot') }}
        needs: pack
        environment:
            name: staging
            url: https://dev.brontosaurus.cz

        steps:
            -   uses: actions/checkout@v4

            -   name: Download artifact
                uses: actions/download-artifact@v4
                with:
                    name: deps

            -   name: Extract files to deploy
                run: |
                    mkdir -p deploy/files
                    unzip brontosaurus-theme.zip -d deploy/files

            -   name: Set up SSH connection
                run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.SERVER_KEYSCAN }}" > ~/.ssh/known_hosts
                    echo "${{ secrets.KEY_PRIVATE }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
                    echo "${{ secrets.KEY_PUBLIC }}" > ~/.ssh/id_rsa.pub

            -   name: Deploy
                run: |
                    bash deploy/deploy.sh ${{ secrets.STAGING_REMOTE_USER_AND_HOST }}:${{ secrets.STAGING_REMOTE_PROJECT_DIR }}/wp-content/themes/brontosaurus-theme
